### ISSUE TITLE
Outline rotation are broken

### ISSUE THREAD

**Issue by Be1zebub** [SneakySqwuid/Circles#8]
Minimal reproduce: <https://github.com/SneakySquid/Circles/blob/master/examples/6_radial_menu.lua>

<video src="https://github.com/user-attachments/assets/dbd9eb1f-e367-4fa5-8e06-fecfb78fe2a0"></video>

## temp workaround im using atm:
replace
```lua
wedge:SetRotation(selected * segment_size)
````
with
```lua
wedge.m_Rotation = selected * segment_size
wedge.m_Dirty = true
```

**Comment by SneakySquid** [comment]
Fixed 👍

**Comment by Be1zebub** [comment]
nope, it doesnt works
<video src="https://github.com/user-attachments/assets/213a8375-ea43-46e0-89c7-7810b58edf13"></video>

**Comment by Be1zebub** [comment]
ty
